import Head from 'next/head';
import Link from 'next/link';
import { sanityClient, urlFor} from '../../lib/sanity';


// groc sanity query
const recipesQuery = `*[_type == 'recipe'] {
  _id,
  name,
  slug,
  mainImage
}
`;
// curly braces {recipes}...called a destructuring assignment.  lets us pick out values inside of the object that is passed through the home function 
export default function Home({ recipes }) {



  return (
    <div >
      <Head>
        <title>Brandon's Kitchen🍅 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

     <h1>Welcome to Brandon's Kitchen🍅 </h1>

<ul>
  {/* if recipes continue on and maping over the list items */}
  {recipes?.length > 0 && recipes.map((recipe)=> (
  <li>
    <Link href='/'>
      <a>
        <img />
        <span>{recipe.name}</span>
      </a>
    </Link>
  </li>
  ))}
</ul>

    </div>
  )
}
//takes in fetch
export async function getStaticProps() {
 const recipes = await sanityClient.fetch(recipesQuery);
 return { props: { recipes }};
}